# Move the directory to the second line
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$golang\
$nodejs\
$python\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character
"""

# Inserts a blank line between shell prompts
add_newline = true

[username]
style_user = "white bold"
style_root = "black bold"
disabled = false
show_always = true
